### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by cellularmitosis** [rurban/clisp#11]
Thanks for your work on clisp!

I ran into the libiconv issue, which was fixed [here](https://github.com/rurban/clisp/issues/4) in 2017, then I realized the last release of clisp (2.49) was 10 years ago, despite hundreds of commits since then.

Seeing all of this progress is great news!  But why has no one made a release in 10 years?

**Comment by rurban** [comment]
Wrong forum. This just a mirror with some patches. You need to ask the maintainers, Bruno Haible and Sam Steingold.
They recently improved the garbage collector to be compacting and generational and this is not quite stable yet. My smokes are all red.

**Comment by cellularmitosis** [comment]
thanks!
